In [15]:
%load_ext autoreload
%autoreload 2

In [16]:
from src.generate_trees import calc_score, two_tail_prob

In [6]:
import pandas as pd
import numpy as np

In [12]:
faunastep = 0.5

In [3]:
detections = pd.DataFrame()

detections["id"] = [0, 1, 2]
detections["time"] = [0, 1, 2]
detections["object_location"] = [0, 0.5, 2]

In [17]:
detections = pd.read_csv('../data/detections.csv')

In [18]:
detections

id  camera_location  time  object_location
0    0              0.0     0         0.292697
1    1              0.5     1         0.323818
2    2              2.0     4         2.433088
3    3              2.0     4         2.430191
4    4              2.5     5         2.391798
5    5              2.5     5         2.494960
6    6              3.0     6         2.513292
7    7              3.0     6         2.537622
8    8              7.0    14         7.162219
9    9              7.5    15         7.119493
10  10              7.5    15         7.801735
11  11              8.0    16         7.801142

In [19]:
n_dets = len(detections)

dists = np.zeros((len(detections), len(detections)))
Dtime = np.zeros((len(detections), len(detections)))
for i in range(n_dets):
    for j in range(n_dets):
        dists[i, j] = np.abs(detections.loc[i]["object_location"] - detections.loc[j]["object_location"])
        Dtime[i, j] = np.abs(detections.loc[i]["time"] - detections.loc[j]["time"])

In [20]:
dists

array([[0.00000000e+00, 3.11211932e-02, 2.14039136e+00, 2.13749401e+00,
        2.09910120e+00, 2.20226277e+00, 2.22059555e+00, 2.24492518e+00,
        6.86952248e+00, 6.82679660e+00, 7.50903816e+00, 7.50844525e+00],
       [3.11211932e-02, 0.00000000e+00, 2.10927017e+00, 2.10637282e+00,
        2.06798001e+00, 2.17114158e+00, 2.18947435e+00, 2.21380398e+00,
        6.83840129e+00, 6.79567540e+00, 7.47791697e+00, 7.47732406e+00],
       [2.14039136e+00, 2.10927017e+00, 0.00000000e+00, 2.89734374e-03,
        4.12901593e-02, 6.18714099e-02, 8.02041884e-02, 1.04533819e-01,
        4.72913112e+00, 4.68640524e+00, 5.36864680e+00, 5.36805390e+00],
       [2.13749401e+00, 2.10637282e+00, 2.89734374e-03, 0.00000000e+00,
        3.83928156e-02, 6.47687537e-02, 8.31015321e-02, 1.07431163e-01,
        4.73202847e+00, 4.68930258e+00, 5.37154414e+00, 5.37095124e+00],
       [2.09910120e+00, 2.06798001e+00, 4.12901593e-02, 3.83928156e-02,
        0.00000000e+00, 1.03161569e-01, 1.21494348e-01, 1.45

In [21]:
z_stat = np.divide(dists,faunastep*Dtime)

/home/nader/Projects/thesis/benthic_targets/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/nader/Projects/thesis/benthic_targets/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [22]:
z_stat

array([[           nan, 6.22423864e-02, 1.07019568e+00, 1.06874701e+00,
        8.39640480e-01, 8.80905107e-01, 7.40198516e-01, 7.48308393e-01,
        9.81360355e-01, 9.10239546e-01, 1.00120509e+00, 9.38555657e-01],
       [6.22423864e-02,            nan, 1.40618011e+00, 1.40424855e+00,
        1.03399000e+00, 1.08557079e+00, 8.75789742e-01, 8.85521594e-01,
        1.05206174e+00, 9.70810772e-01, 1.06827385e+00, 9.96976542e-01],
       [1.07019568e+00, 1.40618011e+00,            nan,            inf,
        8.25803187e-02, 1.23742820e-01, 8.02041884e-02, 1.04533819e-01,
        9.45826225e-01, 8.52073680e-01, 9.76117600e-01, 8.94675649e-01],
       [1.06874701e+00, 1.40424855e+00,            inf,            nan,
        7.67856312e-02, 1.29537507e-01, 8.31015321e-02, 1.07431163e-01,
        9.46405693e-01, 8.52600470e-01, 9.76644390e-01, 8.95158540e-01],
       [8.39640480e-01, 1.03399000e+00, 8.25803187e-02, 7.67856312e-02,
                   nan,            inf, 2.42988695e-01, 2.91

In [23]:
two_tail_prob(z_stat)

array([[       nan, 0.95036981, 0.28453124, 0.28518368, 0.40111   ,
        0.37836918, 0.45917955, 0.45427416, 0.32641507, 0.36269619,
        0.31672767, 0.34795893],
       [0.95036981,        nan, 0.15967065, 0.16024485, 0.30114084,
        0.27766893, 0.38114435, 0.37587538, 0.29277123, 0.33164252,
        0.285397  , 0.3187759 ],
       [0.28453124, 0.15967065,        nan, 0.        , 0.93418525,
        0.90151891, 0.93607486, 0.91674573, 0.34423723, 0.3941732 ,
        0.32900619, 0.3709605 ],
       [0.28518368, 0.16024485, 0.        ,        nan, 0.93879408,
        0.89693235, 0.93377081, 0.91444693, 0.3439417 , 0.3938809 ,
        0.32874523, 0.37070234],
       [0.40111   , 0.30114084, 0.93418525, 0.93879408,        nan,
        0.        , 0.80801415, 0.7705558 , 0.28910201, 0.34438373,
        0.27925813, 0.325353  ],
       [0.37836918, 0.27766893, 0.90151891, 0.89693235, 0.        ,
               nan, 0.97075167, 0.93200316, 0.29965718, 0.35501441,
        0.28852856,

In [34]:
def make_hypothesis_tree(detections, faunastep):
    branches = []
    scores = []

    times = detections.time.unique()
    times.sort()
    
    n_dets = len(detections)

    dists = np.zeros((len(detections), len(detections)))
    Dtime = np.zeros((len(detections), len(detections)))
    for i in range(n_dets):
        for j in range(n_dets):
            dists[i, j] = np.abs(detections.loc[i]["object_location"] - detections.loc[j]["object_location"])
            Dtime[i, j] = np.abs(detections.loc[i]["time"] - detections.loc[j]["time"])

    z_stat = np.divide(dists,faunastep*Dtime)
    probz = two_tail_prob(z_stat)
    
    # todo:
    #     pre-generate probabilities between all the detections

    # go through each timestep
    for t in times:
        print("timestep: {}".format(t))

        # get all detections made at that timestep
        det_t = detections[detections["time"] == t]

        # make some lists to fill
        new_branches = []
        new_scores = []

        # iterate over the detections
        for i, d in det_t.iterrows():
#             print(d["id"])
            if t == 0:
                new_br = np.array([d["id"]])
                new_score = 1

                new_branches.append(new_br)
                new_scores.append(new_score)

            else:
                # create new vector (case where this detection is a new individual)
                new_br = np.empty(t + 1)
                new_br[:] = np.NaN
                new_br[t] = d["id"]

                # add this to the new branches for this timestep
                new_branches.append(new_br)

                # add a score (of zero) for this case
                new_scores.append(1)

                # iterate over existing branches
                for i, br in enumerate(branches):
                    # get the id of the last detection in the current branch
                    last_detection = np.array(br)[np.logical_not(np.isnan(br))][-1]

                    # case where this is a repeat of the last observed
                    new_br_repeat = np.append(br, d["id"])
                    new_branches.append(new_br_repeat)

                    # calculate score
#                     scr = calc_score_row(detections[detections["id"] == last_detection], d, faunastep)
                    
                    scr = probz[int(last_detection), int(d["id"])]

                    #                 print(len(scores), len(new_scores))
                    new_scores.append(scores[i] + scr)

                    # case where it's not
                    new_br_no_repeat = np.append(br, np.NaN)
                    new_branches.append(new_br_no_repeat)

                    new_scores.append(scores[i] + 1 - scr)

            branches = new_branches
            scores = new_scores
    return branches, scores


In [36]:
def make_hypothesis_tree_noscore(detections, faunastep):
    branches = []
#     scores = []

    times = detections.time.unique()
    times.sort()

    # todo:
    #     pre-generate probabilities between all the detections

    # go through each timestep
    for t in times:
        print("timestep: {}".format(t))

        # get all detections made at that timestep
        det_t = detections[detections["time"] == t]

        # make some lists to fill
        new_branches = []
#         new_scores = []

        # iterate over the detections
        for i, d in det_t.iterrows():
#             print(d["id"])
            if t == 0:
                new_br = np.array([d["id"]])
#                 new_score = 1

                new_branches.append(new_br)
#                 new_scores.append(new_score)

            else:
                # create new vector (case where this detection is a new individual)
                new_br = np.empty(t + 1)
                new_br[:] = np.NaN
                new_br[t] = d["id"]

                # add this to the new branches for this timestep
                new_branches.append(new_br)

                # add a score (of zero) for this case
#                 new_scores.append(1)

                # iterate over existing branches
                for i, br in enumerate(branches):
                    # get the id of the last detection in the current branch
                    last_detection = np.array(br)[np.logical_not(np.isnan(br))][-1]

                    # case where this is a repeat of the last observed
                    new_br_repeat = np.append(br, d["id"])
                    new_branches.append(new_br_repeat)

                    # calculate score
#                     scr = calc_score_row(detections[detections["id"] == last_detection], d, faunastep)
                    
#                     scr = probz[int(last_detection), int(d["id"])]

                    #                 print(len(scores), len(new_scores))
#                     new_scores.append(scores[i] + scr)

                    # case where it's not
                    new_br_no_repeat = np.append(br, np.NaN)
                    new_branches.append(new_br_no_repeat)

#                     new_scores.append(scores[i] + 1 - scr)

            branches = new_branches
#             scores = new_scores
    return branches


In [37]:
b, s= make_hypothesis_tree_noscore(detections, faunastep)

timestep: 0
timestep: 1
timestep: 4


KeyboardInterrupt: 